export const DISTRIBUIDORAS = [
  "Enel",
  "Copel",
  "Cemig",
  "CPFL",
  "Neoenergia Brasília",
  "Neoenergia Cosern",
  "Neoenergia Elektro",
  "Neoenergia Coelba",
  "Neoenergia Pernambuco",
  "Celesc",
  "Energisa",
  "Equatorial",
  "RGE",
  "Âmbar Energia",
  "Light",
  "EDP",
  "Coopera",
  "Cerej",
  "Sulgipe",
  "Cerpalo",
  "Cersul",
  "Certrel",
  "Certaja",
  "Outro",
] as const;
